### ISSUE TITLE
Failed to activate the language-haskell-scoped package

### ISSUE THREAD

**Issue by poonamveeral** [atom-haskell/language-haskell-scoped#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [language-haskell-scoped](https://github.com/atom-haskell/language-haskell-scoped) package 0.1.1

### Stack Trace

Failed to activate the language-haskell-scoped package

```
At Invalid or unexpected token

C:\Users\Asus\.atom\packages\language-haskell-scoped\node_modules\@babel\runtime-corejs2\core-js\object\create.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:85:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146396)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147280)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/language-haskell-scoped/node_modules/xregexp/lib/xregexp.js:10:38)
    at /packages/language-haskell-scoped/node_modules/xregexp/lib/xregexp.js:2016:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/language-haskell-scoped/node_modules/xregexp/lib/index.js:10:39)
    at /packages/language-haskell-scoped/node_modules/xregexp/lib/index.js:36:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/language-haskell-scoped/lib/regex.js:3:17)
    at /packages/language-haskell-scoped/lib/regex.js:13:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-haskell 0.4.0 
atom-repl 0.1.0 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
goto 1.8.3 
haskell-ghc-mod 2.2.5 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
ide-haskell 2.4.1 
ide-haskell-cabal 2.3.0 
ide-haskell-hasktags 0.0.16 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.9.0 
intentions 1.1.5 
language-haskell 1.19.1 
language-haskell-scoped 0.1.1 
linter 2.3.1 
linter-ui-default 1.8.0 
```

**Comment by lierdakil** [comment]
I've updated dependencies and released v0.1.2, which should hopefully resolve this issue. Let me know if not.
